version: '3.8'

services:
  # ML Model API
  ml-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    depends_on:
      - mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MLflow Tracking Server
  mlflow:
    image: python:3.10-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlartifacts:/mlflow/mlartifacts
    command: >
      bash -c "pip install mlflow==2.20.0 &&
               mlflow server
               --backend-store-uri /mlflow/mlruns
               --default-artifact-root /mlflow/mlartifacts
               --host 0.0.0.0
               --port 5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlflow/mlruns
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlartifacts

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

volumes:
  mlflow_data:
  prometheus_data: