name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false  # Don't fail the build if Codecov upload fails
        token: ${{ secrets.CODECOV_TOKEN }}  # Optional: Add token when available
      continue-on-error: true  # Continue pipeline even if this step fails
      
    - name: Coverage report summary
      run: |
        echo "Coverage report generated successfully!"
        echo "Coverage file: coverage.xml"
        if [ -f coverage.xml ]; then
          echo "✅ Coverage file exists and ready for analysis"
        else
          echo "❌ Coverage file not found"
        fi

  # Job 2: Data validation and model training
  train:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data validation
      run: |
        echo "Running data validation..."
        python -c "
        import pandas as pd
        import sys
        try:
            data = pd.read_csv('data/heart.csv')
            print(f'✅ Data loaded successfully: {data.shape}')
            assert not data.isnull().any().any(), 'Data contains null values'
            print('✅ Data validation passed')
        except Exception as e:
            print(f'❌ Data validation failed: {e}')
            sys.exit(1)
        "
        
    - name: Train model
      run: |
        python src/train.py
        
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/
          model_version.txt

  # Job 3: Build Docker image with security scanning
  build:
    runs-on: ubuntu-latest
    needs: [test, train]
    permissions:
      contents: read
      packages: write
      security-events: write  # Required for security scanning
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build local image for security scanning
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: heart-disease-prediction:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'heart-disease-prediction:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'  # Focus on critical and high severity
        ignore-unfixed: true       # Ignore unfixed vulnerabilities to reduce noise
      continue-on-error: true      # Don't fail the build on security scan failures
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true  # Don't fail if security upload fails
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Job 4: Deploy to staging (only on main branch)
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Here you would typically deploy to your staging environment
        # For example, updating a Kubernetes deployment or Docker Compose service
        echo "Deployment to staging completed"
        
    - name: Run integration tests
      run: |
        echo "Running integration tests against staging..."
        # Add your integration test commands here
        echo "Integration tests passed"
        
    - name: Notify deployment
      run: |
        echo "✅ Deployment to staging successful"
        echo "🔗 Staging URL: https://staging.your-domain.com"