name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r src/requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Train model
        run: python src/train.py

      - name: List models
        run: ls -la models || true

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/
